config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  get 'posts' => 'posts#index'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments,
           -> { extending WithUserAssociationExtension },
           dependent: :restrict_with_exception, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  # has_many :commented_posts, through: :comments, source: :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

  def create_with_user(attributes = {}, user)
   attributes[:user_] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to posts_path
  end

  def comment_params
    params.require(:comment).permit(:comments)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  # def create
  #   Post.create(post_params)
  #   redirect_to '/posts'
  # end

  def create
    @post = Post.create(post_params)
    # @post.save
    redirect_to '/'
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'post deleted successfully!'
    redirect_to '/posts'
  end

  def post_params
    params.require(:post).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comments %>
  <%= f.submit 'submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <% if user_signed_in? %>
    <%= link_to "sign out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "sign in", new_user_session_path %>
    <%= link_to "sign up", new_user_registration_path %>
  <% end %>

<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/pics/new.html.erb
<!-- UPDATE FORM with actual HTML FORM code -->
<%= form_for @pic do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
<!-- ADD A FRAME HERE SO EACH post IS ON A NEW LINE! -->
      <div>
          <%= link_to post.message, post_path(post) %>
          <%= link_to 'comment', new_post_comment_path(post) %>
          <%= link_to "delete #{post.message}", post_path(post), method: :delete %>
          <% end %>
      </div>

  <% else %>
    <h3> no posts yet! </h3>
<% end %>

<br> <a href=posts/new> add a post </a>

app/views/posts/new.html.erb
<!-- UPDATE FORM with actual HTML FORM code -->
<%= form_for @post do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>
  <%= f.submit %>
<% end %>
<br><a href=/posts> back to all posts </a>

app/views/posts/show.html.erb
<!-- <p> <%= @post.message %> </p> -->

<p> <%= @post.message %> </p>
  <% if @post.comments.any? %>
    <ul>
      <% @post.comments.each do |comment| %>
        <li>
          <%= comment.comments %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p> no comments here! </p>
  <% end %>

<a href=/posts> back to all posts </a>